```{r logregfunc, cache=cacheon}

qivarsuse <- qivarsmeta %>% pull(qivar)

orfunc <- function(xvar, xvarname) {
  for (i in seq_along(qivarsuse)) {
    cl <- class(rsdata %>% pull(!!sym(qivarsuse[i])))

    if (cl == "numeric") {
      out <- rsdata %>%
        filter(!is.na(!!sym(qivarsuse[i])) & !is.na(!!sym(xvar))) %>%
        group_by(!!sym(xvar), .drop = FALSE) %>%
        summarise(
          med = fn(median(!!sym(qivarsuse[i]), na.rm = TRUE), 1),
          q1 = fn(quantile(!!sym(qivarsuse[i]), 0.25, na.rm = TRUE), 1),
          q3 = fn(quantile(!!sym(qivarsuse[i]), 0.75, na.rm = TRUE), 1)
        ) %>%
        ungroup() %>%
        mutate(
          out = paste0(med, " [", q1, "-", q3, "]"),
          out = if_else(out == "NA [NA-NA]", "-", out)
        ) %>%
        select(!!sym(xvar), out) %>%
        pivot_wider(names_from = !!sym(xvar), values_from = out)

      out <- bind_cols(
        QI = qivarsuse[i], out,
        "Crude OR (95% CI), p-value" = "-",
        "Adjusted OR (95% CI), p-value" = "-"
      )
    }
    if (cl == "factor") {
      lev <- levels(rsdata %>% pull(!!sym(qivarsuse[i])))

      out <- rsdata %>%
        filter(!is.na(!!sym(qivarsuse[i])) & !is.na(!!sym(xvar))) %>%
        group_by(!!sym(xvar), .drop = FALSE) %>%
        count(!!sym(qivarsuse[i]), .drop = FALSE) %>%
        mutate(
          tot = sum(n),
          p = fn(n / tot * 100, 1),
          np = paste0(n, "/", tot, " (", p, "%)"),
          np = if_else(np == "0/0 (NaN%)", "-", np)
        ) %>%
        filter(!!sym(qivarsuse[i]) == lev[2]) %>%
        ungroup() %>%
        select(!!sym(xvar), np) %>%
        pivot_wider(names_from = !!sym(xvar), values_from = np)

      if (rsdata %>%
        filter(!is.na(!!sym(qivarsuse[i])) & !is.na(!!sym(xvar))) %>%
        count(!!sym(qivarsuse[i]), !!sym(xvar)) %>% nrow() == 4) {
        mod <- summary(glm(formula(paste0(qivarsuse[i], " == '", lev[2], "' ~ ", xvar)),
          family = "binomial",
          data = rsdata
        ))

        orcrude <- paste0(
          fn(exp(mod$coefficients[2, "Estimate"]), 2),
          " (",
          fn(exp(mod$coefficients[2, "Estimate"] - global_z05 * mod$coefficients[2, "Std. Error"]), 2),
          "-",
          fn(exp(mod$coefficients[2, "Estimate"] + global_z05 * mod$coefficients[2, "Std. Error"]), 2),
          "), ",
          fn(mod$coefficients[2, "Pr(>|z|)"], 3, p = T)
        )

        modvarsuse <- modvars[!modvars %in% str_split(qivarsmeta %>% filter(qivar == qivarsuse[i]) %>% pull(noadjvars), ", ")[[1]]]
        kontvars <- c("shf_age", "shf_bpsys", "shf_heartrate", "shf_bmiimp", "shf_gfrckdepi", "shf_ntprobnp")
        for (j in seq_along(kontvars)) {
          modvarsuse <- str_replace(modvarsuse, kontvars[j], paste0("ns(", kontvars[j], ", df = 4)"))
        }

        modadj <- with(imp, glm(formula(paste0(
          qivarsuse[i], " == '", lev[2], "' ~ ",
          xvar, " + ", paste(modvarsuse, collapse = " + ")
        )),
        family = binomial(link = "logit")
        ))
        smodadj <- summary(pool(modadj))

        oradj <- paste0(
          fn(exp(smodadj$estimate[2]), 2),
          " (",
          fn(exp(smodadj$estimate[2] - global_z05 * smodadj$std.error[2]), 2),
          "-",
          fn(exp(smodadj$estimate[2] + global_z05 * smodadj$std.error[2]), 2),
          "), ",
          fn(smodadj$p.value[2], dig = 3, p = TRUE)
        )

        out <- bind_cols(
          QI = qivarsuse[i], out,
          "Crude OR (95% CI), p-value" = orcrude,
          "Adjusted OR (95% CI), p-value" = oradj
        )
      } else {
        out <- bind_cols(
          QI = qivarsuse[i], out,
          "Crude OR (95% CI), p-value" = "-",
          "Adjusted OR (95% CI), p-value" = "-"
        )
      }
    }

    if (i == 1) {
      outtab <<- out
    } else {
      outtab <<- bind_rows(outtab, out)
    }
  }

  outtab <- left_join(outtab,
    qivarsmeta %>% select(qivar, qilongname),
    by = c("QI" = "qivar")
  ) %>%
    select(-QI) %>%
    select(qilongname, everything()) %>%
    rename(QI = qilongname)

  write.xlsx(outtab, paste0("./output/tabs/Likelihood of attainment by ", xvarname, "_", Sys.Date(), ".xlsx"),
    rowNames = FALSE, overwrite = TRUE
  )

  outtab <- outtab %>%
    mutate(across(everything(), sanitize_text))

  colnames(outtab) <- sanitize_text(colnames(outtab))

  ref <- levels(rsdata %>% pull(!!sym(xvar)))[1]
  footnote(default_kable(outtab,
    font_size = 6,
    caption = sanitize_text(paste0("Likelihood of attainment by ", xvarname)),
    escape = FALSE
  ),
  general = paste0("Reference in the logistic regression model is ", ref)
  )
}
```

```{r logregef, cache=cacheon, dependson="logregfunc"}
orfunc(xvar = "shf_ef_cat", xvarname = "EF")
```

```{r logreglocation, cache=cacheon, dependson="logregfunc"}
orfunc("shf_location", "location")
```

```{r logregsex, cache=cacheon, dependson="logregfunc"}
orfunc("shf_sex", "sex")
```

```{r logregage, cache=cacheon, dependson="logregfunc"}
orfunc("shf_age_cat", "age")
```
