```{r tab1, cache=cacheon}

tab1 <- print(CreateTableOne(
  vars = tabvars,
  data = rsdata
),
smd = FALSE,
missing = TRUE,
printToggle = FALSE,
nonnormal = tabvars,
catDigits = 1,
contDigits = 1,
noSpaces = TRUE,
explain = FALSE,
showAllLevels = TRUE
)
tab1 <- as_tibble(cbind(var = rownames(tab1), tab1)) %>%
  select(var, level, Missing, Overall)


hosptab <- tibble(var = NA, level = NA, hosp = NA)
for (i in seq_along(tabvars)) {
  cl <- class(rsdata %>% pull(!!sym(tabvars[i])))

  if (cl == "numeric") {
    ds <- rsdata %>%
      group_by(shf_centre) %>%
      summarise(
        ds = median(!!sym(tabvars[i]), na.rm = TRUE),
        n = n()
      ) %>%
      ungroup() %>%
      filter(n >= 10)

    out <- ds %>%
      summarise(
        med = fn(median(ds, na.rm = T), dig = 1),
        q1 = fn(quantile(ds, probs = 0.25, na.rm = T), dig = 1),
        q3 = fn(quantile(ds, probs = 0.75, na.rm = T), dig = 1)
      ) %>%
      mutate(hosp = paste0(med, " [", q1, "-", q3, "]")) %>%
      mutate(
        level = NA,
        var = if_else(row_number() == 1, tabvars[i], NA_character_)
      ) %>%
      select(var, level, hosp)
  }

  if (cl %in% c("factor", "character")) {
    if (cl == "character") {
      ds <- rsdata %>%
        mutate(!!sym(tabvars[i]) := factor(!!sym(tabvars[i])))
    }

    ds <- rsdata %>%
      filter(!is.na(!!sym(tabvars[i]))) %>%
      group_by(shf_centre) %>%
      count(!!sym(tabvars[i]), .drop = FALSE) %>%
      mutate(
        ntot = sum(n),
        ds = n / ntot * 100
      ) %>%
      ungroup() %>%
      filter(ntot >= 10)

    out <- ds %>%
      group_by(!!sym(tabvars[i])) %>%
      summarise(
        med = fn(median(ds, na.rm = T), dig = 1),
        q1 = fn(quantile(ds, probs = 0.25, na.rm = T), dig = 1),
        q3 = fn(quantile(ds, probs = 0.75, na.rm = T), dig = 1)
      ) %>%
      mutate(hosp = paste0(med, " [", q1, "-", q3, "]")) %>%
      rename(level = !!sym(tabvars[i])) %>%
      mutate(var = if_else(row_number() == 1, tabvars[i], NA_character_)) %>%
      select(var, level, hosp)
  }
  hosptab <- bind_rows(hosptab, out)
}

tab1 <- bind_cols(tab1, hosptab %>% select(hosp))

tab1 <- tab1 %>%
  # to get labs and units in place
  mutate(
    # if recoding or categorizing will still get org label
    vartmp = str_replace_all(var, "(_cat2|_cat)", ""),
    # if shf/sos combination  will still get org label
    vartmp = str_replace_all(vartmp, "shf_sos_com_", "sos_com_")
  )

tab1 <- left_join(tab1,
  meta.variables.Sheet.1 %>%
    select(variable, label, unit),
  by = c("vartmp" = "variable")
) %>%
  mutate(
    Variable = coalesce(label, var),
    Variable = if_else(!is.na(unit),
      paste0(Variable, " (", unit, ")"),
      Variable
    )
  )

write.xlsx(tab1 %>% select(Variable, level:hosp), paste0("./output/tabs/Baseline characteristics_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = TRUE)

# footnotes
tab1 <- tab1 %>%
  mutate(
    footnote1 = if_else(str_detect(var, "^shf_") |
      var %in% c("PARTICIPATION_HF_SCHOOL", "PARTICIPATION_HF_TRAINING", "FOLLOWUP_UNIT"),
    footnote_marker_symbol(1), ""
    ),
    footnote2 = if_else(str_detect(var, "sos_"), footnote_marker_symbol(2), ""),
    footnote3 = if_else(str_detect(var, "scb_"), footnote_marker_symbol(3), ""),
    footnote4 = if_else(var %in% modvars, footnote_marker_symbol(4), ""),
    footnote5 = if_else(str_detect(var, "scb_dispincome"), footnote_marker_symbol(5), "")
  ) %>%
  unite(footnote, starts_with("footnote"), sep = "") %>%
  mutate(
    # so no probs
    Variable = sanitize_text(Variable),
    Variable = paste0(Variable, footnote),
    level = sanitize_text(level)
  ) %>%
  select(Variable, level:hosp)

## fix in order to use escape = TRUE
colnames(tab1) <- sanitize_text(c("Variable", "Level", "Missing (%)", "Overall", "Hospital variation median [q1-q3]"))

footnote(
  default_kable(tab1,
    font_size = 6,
    caption = "Baseline characteristics",
    longtable = TRUE,
    escape = FALSE
  ),
  general = c(
    "Categorical variables are presented with n (%) and continuous variables with median [q1-q3].",
    "The hospital variation is the median [q1-q3] of the median (continuous variables) or proportion (categorical variables)."
  ),
  symbol = c(
    "Source: SwedeHF",
    "Source: SoS",
    "Source: SCB",
    "Included in imputation model and adjusted for in cox and logistic regression models.",
    "According to tertiles within indexyear and sex"
  )
)
```

```{r tab1byvars, cache=cacheon}

tab1func <- function(stratavar) {
  tab1 <- print(CreateTableOne(
    vars = tabvars,
    data = rsdata,
    strata = stratavar
  ),
  smd = FALSE,
  missing = FALSE,
  printToggle = FALSE,
  nonnormal = tabvars,
  catDigits = 1,
  contDigits = 1,
  noSpaces = TRUE,
  explain = FALSE,
  showAllLevels = TRUE
  )
  tab1 <- as_tibble(cbind(var = rownames(tab1), tab1)) %>%
    select(-test)
}

tab1ef <- tab1func(stratavar = "shf_ef_cat")
tab1sex <- tab1func(stratavar = "shf_sex")
tab1age <- tab1func(stratavar = "shf_age_cat")
tab1location <- tab1func(stratavar = "shf_location")

tab1 <- bind_cols(
  tab1ef,
  tab1location %>% select(-var, -level),
  tab1sex %>% select(-var, -level),
  tab1age %>% select(-var, -level)
)

tab1 <- tab1 %>%
  # to get labs and units in place
  mutate(
    # if recoding or categorizing will still get org label
    vartmp = str_replace_all(var, "(_cat2|_cat)", ""),
    # if shf/sos combination  will still get org label
    vartmp = str_replace_all(vartmp, "shf_sos_com_", "sos_com_")
  )

tab1 <- left_join(tab1,
  meta.variables.Sheet.1 %>%
    select(variable, label, unit),
  by = c("vartmp" = "variable")
) %>%
  mutate(
    Variable = coalesce(label, var),
    Variable = if_else(!is.na(unit),
      paste0(Variable, " (", unit, ")"),
      Variable
    )
  )

write.xlsx(tab1 %>% select(Variable, level:p...14),
  paste0("./output/tabs/Baseline characteristics by LVEF, location, sex and age_", Sys.Date(), ".xlsx"),
  rowNames = FALSE, overwrite = TRUE
)

# footnotes

tab1 <- tab1 %>%
  mutate(
    footnote1 = if_else(str_detect(var, "^shf_") |
      var %in% c("PARTICIPATION_HF_SCHOOL", "PARTICIPATION_HF_TRAINING", "FOLLOWUP_UNIT"),
    footnote_marker_symbol(1), ""
    ),
    footnote2 = if_else(str_detect(var, "sos_"), footnote_marker_symbol(2), ""),
    footnote3 = if_else(str_detect(var, "scb_"), footnote_marker_symbol(3), ""),
    footnote4 = if_else(var %in% modvars, footnote_marker_symbol(4), ""),
    footnote5 = if_else(str_detect(var, "scb_dispincome"), footnote_marker_symbol(5), "")
  ) %>%
  unite(footnote, starts_with("footnote"), sep = "") %>%
  mutate(
    # so no probs
    Variable = sanitize_text(Variable),
    Variable = paste0(Variable, footnote),
    level = sanitize_text(level)
  ) %>%
  select(Variable, level:p...14) %>%
  rename(Level = level)

## fix in order to use escape = TRUE
colnams <- colnames(tab1)
colnams[str_detect(colnams, "^p")] <- "p-value"
colnames(tab1) <- sanitize_text(colnams)

footnote(
  default_kable(tab1,
    font_size = 3,
    caption = "Baseline characteristics by LVEF, location, sex and age",
    longtable = TRUE,
    escape = FALSE
  ) %>%
    landscape() %>%
    add_header_above(c(" " = 1, " " = 1, "LVEF" = 3, "Location" = 3, "Sex" = 3, "Age" = 3)),
  general = c(
    "Categorical variables are presented with n (%) and tested with chi-square test and continuous variables with median [q1-q3] and tested with Kruskal-Wallis test."
  ),
  symbol = c(
    "Source: SwedeHF",
    "Source: SoS",
    "Source: SCB",
    "Included in imputation model and adjusted for in cox and logistic regression models.",
    "According to tertiles within indexyear and sex"
  )
)
```
